// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkexpfsygsmrnhnykwzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZXhwZnN5Z3Ntcm5obnlrd3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTEzMzMsImV4cCI6MjA1ODIyNzMzM30.UZyt8EcbJMIfwYMRRH1FA6vCV6amXk7urNHq4xLO3GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);